bmaptools/CLI.py: Print help in case of no arguments
Avoids the run-time exception on systems with python3 as the default
python version (python2 requires a subparser so it fails on empty args):

    $ bmaptool
    Traceback (most recent call last):
      File "/usr/bin/bmaptool", line 11, in <module>
        load_entry_point('bmap-tools==3.4', 'console_scripts', 'bmaptool')()
      File "/usr/lib/python3.6/site-packages/bmaptools/CLI.py", line 715, in main
        args.func(args)
    AttributeError: 'Namespace' object has no attribute 'func'

Suggested by: Simon McVittie [https://github.com/intel/bmap-tools/pull/51#issuecomment-398161212]