CLI: python3: Fix copying images from URLs
When copying an image from a remote host we first create a temporary copy
of the bmap and signature files locally. Because Python 3 distinguishes
between (Unicode) text strings and byte sequences, we have to be
consistent about copying from a binary file to a binary file: writing
byte sequences to a text file is no longer allowed.

This patch fixes the following crash:

    ```
    sudo bmaptool copy  http://****.com/qtec/europa/images/qt5022/qimage-dev-qt5022.wic  /dev/sdb
    bmaptool: info: discovered bmap file 'http://tftp.qtec.com/qtec/europa/images/qt5022/qimage-dev-qt5022.wic.bmap'
    Traceback (most recent call last):
      File "/usr/bin/bmaptool", line 11, in <module>
        sys.exit(main())
      File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 715, in main
        args.func(args)
      File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 423, in copy_command
        open_files(args)
      File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 365, in open_files
        (bmap_obj, bmap_path) = find_and_open_bmap(args)
      File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 335, in find_and_open_bmap
        shutil.copyfileobj(bmap_obj, tmp_obj)
      File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
        fdst.write(buf)
      File "/usr/lib/python3.6/tempfile.py", line 622, in func_wrapper
        return func(*args, **kwargs)
    TypeError: write() argument must be str, not bytes
    ```

[Commit message amended by Artem Bityutskiy]
Change-Id: Ie49080216e57eb30b8cd8b3fce11d9b7ba5ef349
Signed-off-by: Ricardo Ribalda Delgado <ricardo.ribalda@gmail.com>