Fix python2 compatibility
The tool was originally written for python2, then was converted to python3.
Part of the conversion was usin 'with_traceback()', which does not exist
in python2. When reading a corrupted image, bmaptool fails like this under
python2:

[abityuts@abityuts-desk bmap-tools (master)]$ python2.7 ./bmaptool copy ~/tmp/bmap/image.raw.bz2 ~/tmp/file
bmaptool: info: discovered bmap file '/home/abityuts/tmp/bmap/image.raw.bmap'
bmaptool: info: block map format version 2.0
bmaptool: info: 250000 blocks of size 4096 (976.6 MiB), mapped 125 blocks (500.0 KiB or 0.1%)
bmaptool: info: copying image 'image.raw.bz2' to file 'file' using bmap file 'image.raw.bmap'
bmaptool: info: 100% copied
Traceback (most recent call last):
  File "./bmaptool", line 11, in <module>
    sys.exit(main())
  File "/home/abityuts/git/bmap-tools/bmaptools/CLI.py", line 715, in main
    args.func(args)
  File "/home/abityuts/git/bmap-tools/bmaptools/CLI.py", line 477, in copy_command
    writer.copy(False, not args.no_verify)
  File "/home/abityuts/git/bmap-tools/bmaptools/BmapCopy.py", line 584, in copy
    raise exc_info[1].with_traceback(exc_info[2])
AttributeError: 'Error' object has no attribute 'with_traceback'

This patch fixes the problem.

This patch started using the 'six' module which makes compatibility easier
support.

Change-Id: Ib08c14a4713e5dd80fbf20b6c23ebbc769c16ba9
Signed-off-by: Artem Bityutskiy <artem.bityutskiy@intel.com>